name: Windows
on:
  workflow_dispatch:
       
jobs:               
  build:
    strategy:
      matrix:
        arch : [x86,x64,amd64_arm64]
        include:
         - arch : x86
           bindings : '-DZ3_BUILD_PYTHON_BINDINGS=True'
         - arch : x64
           bindings: '-DZ3_BUILD_PYTHON_BINDINGS=True -DZ3_BUILD_DOTNET_BINDINGS=True -DZ3_BUILD_JAVA_BINDINGS=True'
         - arch : amd64_arm64
           bindings: '-DZ3_BUILD_PYTHON_BINDINGS=True'

    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |          
          cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}            
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${{ matrix.bindings }}
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
      - name: Test
        run: |
         call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" $(arch)
         pushd python
         python z3test.py z3
         python z3test.py z3num
         popd
         cmake --build build --config ${{ env.BUILD_TYPE }}  cpp_example
         examples\cpp_example_build_dir\cpp_example.exe
         cmake --build build --config ${{ env.BUILD_TYPE }}  c_example
         examples\c_example_build_dir\c_example.exe
         cmake --build build --config ${{ env.BUILD_TYPE }}  test-z3
         test-z3.exe -a

